### PR TITLE
Add atompair overlap radii and energy table and ability to read XTC trajectory files.

### LINKED ISSUE #138: Add XTC trajectory file reading capablility to Cassandra
Cassandra already has a trajectory reader, but it would be useful to give it the ability to read XTC files, since they take less storage space than a combination of a `.xyz` file and a `.H` file, and they are able to be directly written by other simulation engines such as GROMACS and LAMMPS.

### LINKED ISSUE #139: Use precalculated atom pair energy table to estimate CBMC energies
Since nonbonded energy calculations for CBMC trials are already rough and don't need to be precise (since they are used only for biasing), they could be more quickly estimated from a table of precalculated intermolecular atom pair energies as a discretized function of the square of atomic separation.

### LINKED ISSUE #140: Add atompair-specific overlap radii for use in Widom insertions
The general overlap radius specified in the input file is low enough to guarantee that Widom insertions with significant `widom_var` values are not flagged as having overlap, but there are many Widom insertions with insignificant `widom_var` that are not flagged as overlap by the general overlap radius because different atoms have different sizes and the minimum intermolecular atomic separation that can be found between two atoms in any Widom insertion with significant `widom_var` depends on the identity of the two atoms.

Therefore, it would be beneficial to make Cassandra able to use a relatively short Widom insertion simulation to estimate overlap radii that are specific to each pair of atom identities that can possibly interact in an intermolecular context during a Widom insertion such that no more than a given tolerance fraction of the total `widom_var` sum may be lost by flagging overlaps with these overlap radii.  Cassandra should also be able to read these estimated overlap radii from a file and use them to detect overlap during a larger Widom insertion simulation to increase speed.

It would also be beneficial to make Cassandra able to compute atom type pair-specific overlap radii from a given maximum desired single-atompair intermolecular energy the user is confident is larger than any single-atompair intermolecular energy that can be found in any Widom insertion with significant `widom_var`.  Cassandra should be able to use this method while estimating atompair-specific overlap radii.

### PR DESCRIPTION
**Pull request by rwsmith7531**
## Description
This PR implements the changes proposed in the linked issues.

## Related Issue
Closes #138 
Closes #139 
Closes #140 

## How Has This Been Tested?
This has been tested by computing Henry's constants of difluoromethane and pentafluoroethane in 5 ionic liquids with and without these features, except for the XTC trajectory reading.  XTC trajectory reading was tested by comparing coordinates and properties output by Cassandra when reading a trajectory from a short XTC file with those output when reading the same trajectory from a .xyz file and .H file.

## Backward Compatibility
This does not break backward compatibility for inputs.

## Post Submission Checklist
Please check the fields below as they are completed

- [x] Suitable new documentation files and/or updates to the existing docs are included.
- [x] One or more example input decks are included.
- [x] Suitable tests were added to the test suite
- [x] My name is in the contributor list at `/Documentation/source/reference/acknowledgements.rst`

## Further Information, Files, and Links

### CODE REVIEW

**Comment by emarinri** [comment]
Thanks Ryan!

We discussed that pkg-config could be substituted by the actual flags it returns at compile time. This might save the inclusion of a dependency that is not strictly necessary. I had to install pkg-config  in my local machine so that might be the case in other systems as well.

**Comment by emarinri** [comment]
The makefiles with XTC and without XTC support include the files xtc_routines.f90 and xtc_routines.no_xtc.f90, respectively. If the user compiles the code with no XTC support and sets activates XTC support in the input file, the code will use the xtc_routines.no_xtc.f90 functions which throw an error letting the user know that the executable does not have the XTC implementation.

**Comment by emarinri** [comment]
Could you please include an example of the input file format for the adaptive and specific Rcutoff option?

**Comment by rwsmith7531** [comment]
> Thanks Ryan!
> 
> We discussed that pkg-config could be substituted by the actual flags it returns at compile time. This might save the inclusion of a dependency that is not strictly necessary. I had to install pkg-config in my local machine so that might be the case in other systems as well.

I have now done this.

**Comment by emarinri** [comment]
An improvement included in this PR is the implementation of a pretabulated potential based on an atom ID pair.  

In summary, a pretabulated potential for an atom ID pair is built before a simulation is carried out. This table is used when performing regrowth moves, insertion, deletion or any other CBMC move. It is used when computing the intermolecular pairwise interaction that is used to generate any trial biases that require intermolecular energies, such as insertions or regrowths. For example, when a regrowth move is performed, a set of trial dihedral orientations are proposed. The code measures the distances and if they are within the CBMC cut, it looks up the energy in these atom ID pair tables. No interpolation is performed. The energies for each trial are then used to construct the CBMC trial weights. The same tables are used to construct the weights of the reverse move. The energy change that is used to accept the new configuration is still computed normally.

**Pull request merged**
