### PR TITLE
Correct dimension labels in Apply_PBC_Anint.

### LINKED ISSUE #95: PBC box images based on wrong dimension
## Expected behavior
`Apply_PBC_Anint` in `minimum_image_separation.f90` should apply periodic boundary conditions to all three box dimensions, with the box image in each dimension being dependent on the parent coordinate in the corresponding dimension.

## Current behavior
`Apply_PBC_Anint`, when applying PBC to cubic boxes, bases the y and z box images on the x parent coordinate, not the y or z parent coordinates.

## Steps to reproduce
1. Load unwrapped xyz configuration (not from Cassandra because Cassandra only keeps wrapped coordinates)
2. Write the configuration xyz file from Cassandra
3.  See that y and z coordinates have not been wrapped properly by Cassandra (they can be far outside the box and even different from loaded, unwrapped config)

## Possible solution (optional)
Correct the dimension labels in the code for `Apply_PBC_Anint`.

## Additional context
This bug was discovered when testing Cassandra's trajectory reader (still in development) on unwrapped trajectories from LAMMPS.

### PR DESCRIPTION
**Pull request by rwsmith7531**
## Description
I corrected the dimension labels in the determination of the y and z box images to the corresponding dimension.

## Related Issue
Closes #95

### CODE REVIEW

**Comment by rsdefever** [comment]
If I'm reading this correctly, this is inside (this)[https://github.com/MaginnGroup/Cassandra/pull/96/files#diff-b6c5804f354eb3d23426749baca324829fa997dcc7a28fddf1c99151e7730c4dL141] if statement block:

```fortran
  IF (l_cubic(ibox)) THEN
```

So then the code is correct prior to your PR, right?

**Comment by rwsmith7531** [comment]
> If I'm reading this correctly, this is inside (this)[https://github.com/[/pull/96](https://github.com/MaginnGroup/Cassandra/pull/96)/files#diff-b6c5804f354eb3d23426749baca324829fa997dcc7a28fddf1c99151e7730c4dL141] if statement block:
> 
> ```fortran
>   IF (l_cubic(ibox)) THEN
> ```
> 
> So then the code is correct prior to your PR, right?

It is inside that block, but the code is absolutely not correct before this PR.  Even if the box is cubic, the y and z box images will not necessarily be the same as the x box image.  For example, consider a point at (10, 50, 150) in a 30-angstrom cubic box.  Since the x parent coordinate is inside the box, the code previously implemented would assume that the y and z coordinates are also inside the box, even though they are far outside it, and they would not be wrapped at all.

**Comment by rsdefever** [comment]
>  Even if the box is cubic, the y and z box images will not necessarily be the same as the x box image.

Ah, yes, sorry, my brain was scrambled. This fix looks correct to me. LGTM.

Question: Prior to the addition of your trajectory reader, when was this function called from within the code?

**Comment by rwsmith7531** [comment]
@rsdefever An example that I actually got in the results:  It transformed
[49.384017503474645     23.740517503474642    -70.50738249652535]
into
[-15.5459942007103       -41.1894942007103       -135.437394200710]
in a cubic box with side length = 32.465 Angstroms centered at [0 0 0]

**Comment by rwsmith7531** [comment]
@rsdefever This was called from `Read_Checkpoint` and `Read_Config` in `read_write_checkpoint.f90`, but only when the box is cubic.  It is also called in `min.f90`, but that file isn't included when Cassandra is compiled.

**Comment by rsdefever** [comment]
I'm trying to come up with an example where this fails **before your PR but works after your PR** -- not for the trajectory reader part, but for starting from a configuration. The reason I want to do this is to understand the extent of (what, if anything) was broken beforehand. However, I am having trouble with this.

Here is a contrived example with a single molecule where the molecule starts out 2 boxes outside in ``z`` but inside the box in `y` and `x`. If you look at the first frame of `nvt.out.xyz`, everything has been wrapped properly (before your fix).
[example.zip](https://github.com/MaginnGroup/Cassandra/files/6108989/example.zip)

**Comment by rwsmith7531** [comment]
@rsdefever I modified your example so that it has another molecule shifted +10 in the y dimension from the original molecule, so that we could see what happens to a molecule that isn't subjected to a move attempt.  As expected, the molecule that wasn't subjected to the move attempt ended up outside the box, but not in its original location, strangely.  I looked into why that is, and apparently `Fold_Molecule`, which only shifts by one box image, is called in `main.f90` on every molecule in the simulation.  Your molecule was only 2 box images out, so it got shifted by one box image in the main program, then again by one box image (bringing it inside the simulation box) when it was moved.  Its clone, which I added, was only shifted by one box image in the main program, leaving it still one box image out.
[example2.zip](https://github.com/MaginnGroup/Cassandra/files/6109991/example2.zip)

**Comment by rsdefever** [comment]
@rwsmith7531 thanks!

**Pull request merged**
